package projet.light.off;

import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;



/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Raphaël
 */


public class FenetrePrincipale extends javax.swing.JFrame {
    GrilleDeCellules grille;
    int nbCoups;
    boolean challengeActive;

int i;

    /**
     * Creates new form FenetrePrincipale
     */
    

public FenetrePrincipale() {
        
        challengeActive=false;
        nbCoups = 0;
        initComponents();
        int nbLignes = 10;
        int nbColonnes = 10;
        getContentPane().add(PanneauGrille, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60,
        nbColonnes*40, nbLignes*40));
        this.pack();
        this.revalidate();
    
    PanneauBoutonsVerticaux.setLayout(new GridLayout(nbLignes, 1));
    getContentPane().add(PanneauBoutonsVerticaux, new
    org.netbeans.lib.awtextra.AbsoluteConstraints(45, 57, 1 * 40, nbLignes * 40));
    this.pack();
    this.revalidate();
        this.grille = new GrilleDeCellules(nbLignes, nbColonnes);
        PanneauGrille.setLayout(new GridLayout(nbLignes, nbColonnes));
        for (int i=0; i < nbLignes; i++) {
 for (int j=0; j < nbColonnes; j++ ) {
 CelluleGraphique bouton_cellule = new CelluleGraphique( grille.matriceCellules[i][j], 36,36);
 PanneauGrille.add(bouton_cellule); // ajout au Jpanel PanneauGrille
 
 }   }
 PanneauBoutonsHorizontaux.setLayout(new GridLayout(1, nbColonnes));
    getContentPane().add(PanneauBoutonsHorizontaux, new
    org.netbeans.lib.awtextra.AbsoluteConstraints(89, 15,  nbColonnes* 40, 1* 40));
    this.pack();
    this.revalidate();

 // création du panneau de boutons horizontaux (pour les lignes)
 for (i = 0; i < nbColonnes; i++) {
 JButton bouton_colonne = new JButton();
 ActionListener ecouteurClick = new ActionListener() {
 final int j = i;
 @Override
 public void actionPerformed(ActionEvent e) {
 grille.activerColonneDeCellules(j);
repaint();
finpartie();
 }
 };
 bouton_colonne.addActionListener(ecouteurClick);
 PanneauBoutonsHorizontaux.add(bouton_colonne);

 }

 // création du panneau de boutons verticaux (pour les lignes)
 for (i = 0; i < nbLignes; i++) {
 JButton bouton_ligne = new JButton();
 ActionListener ecouteurClick = new ActionListener() {
 final int j = i;
 @Override
 public void actionPerformed(ActionEvent e) {
 grille.activerLigneDeCellules(j);
repaint();
finpartie();
 }
 };
 bouton_ligne.addActionListener(ecouteurClick);
 PanneauBoutonsVerticaux.add(bouton_ligne);
getContentPane().add(Boutondiago, new
    org.netbeans.lib.awtextra.AbsoluteConstraints(45, 15,  1* 40, 1* 40));

getContentPane().add(boutondiago2, new
    org.netbeans.lib.awtextra.AbsoluteConstraints(495, 15,  1* 40, 1* 40));
 }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanneauGrille = new javax.swing.JPanel();
        PanneauBoutonsVerticaux = new javax.swing.JPanel();
        PanneauBoutonsHorizontaux = new javax.swing.JPanel();
        Boutondiago = new javax.swing.JButton();
        boutondiago2 = new javax.swing.JButton();
        Affichercoups = new javax.swing.JTextField();
        chalenge = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanneauGrille.setBackground(new java.awt.Color(0, 0, 0));
        PanneauGrille.setForeground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout PanneauGrilleLayout = new javax.swing.GroupLayout(PanneauGrille);
        PanneauGrille.setLayout(PanneauGrilleLayout);
        PanneauGrilleLayout.setHorizontalGroup(
            PanneauGrilleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
        );
        PanneauGrilleLayout.setVerticalGroup(
            PanneauGrilleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
        );

        getContentPane().add(PanneauGrille, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 360, 360));

        PanneauBoutonsVerticaux.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout PanneauBoutonsVerticauxLayout = new javax.swing.GroupLayout(PanneauBoutonsVerticaux);
        PanneauBoutonsVerticaux.setLayout(PanneauBoutonsVerticauxLayout);
        PanneauBoutonsVerticauxLayout.setHorizontalGroup(
            PanneauBoutonsVerticauxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        PanneauBoutonsVerticauxLayout.setVerticalGroup(
            PanneauBoutonsVerticauxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
        );

        getContentPane().add(PanneauBoutonsVerticaux, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 40, 360));

        PanneauBoutonsHorizontaux.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout PanneauBoutonsHorizontauxLayout = new javax.swing.GroupLayout(PanneauBoutonsHorizontaux);
        PanneauBoutonsHorizontaux.setLayout(PanneauBoutonsHorizontauxLayout);
        PanneauBoutonsHorizontauxLayout.setHorizontalGroup(
            PanneauBoutonsHorizontauxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
        );
        PanneauBoutonsHorizontauxLayout.setVerticalGroup(
            PanneauBoutonsHorizontauxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 22, Short.MAX_VALUE)
        );

        getContentPane().add(PanneauBoutonsHorizontaux, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 360, -1));

        Boutondiago.setBackground(new java.awt.Color(204, 204, 255));
        Boutondiago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoutondiagoActionPerformed(evt);
            }
        });
        getContentPane().add(Boutondiago, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 40, 30));

        boutondiago2.setBackground(new java.awt.Color(204, 204, 255));
        boutondiago2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutondiago2ActionPerformed(evt);
            }
        });
        getContentPane().add(boutondiago2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 20, 40, 30));

        Affichercoups.setEditable(false);
        Affichercoups.setBackground(new java.awt.Color(204, 204, 255));
        getContentPane().add(Affichercoups, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 170, 140, 80));

        chalenge.setBackground(new java.awt.Color(204, 204, 255));
        chalenge.setText("Défis");
        chalenge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chalengeActionPerformed(evt);
            }
        });
        getContentPane().add(chalenge, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 100, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BoutondiagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoutondiagoActionPerformed
         grille.activerDiagonaleDescendante();
         repaint();
         finpartie();
    
    }//GEN-LAST:event_BoutondiagoActionPerformed
    private void finpartie() {
        nbCoups ++;
        chalenge.setVisible(false);
    if (challengeActive==true && nbCoups >= 12) {
        // Code pour gérer la fin du jeu après 20 coups en mode challenge
        // Par exemple, afficher un message, réinitialiser le jeu, etc.
        System.out.println("Fin du jeu en mode challenge après 20 coups !");
        Fenetrechalenge f2 = new Fenetrechalenge();
        f2.setVisible(true);
        setVisible(false);
    } else {
       
        Affichercoups.setText("Coups effectués : " + nbCoups);

        if (grille.cellulesToutesEteintes()) {
            // ... le reste de votre code ...
            FenetreVictoire f = new FenetreVictoire(nbCoups);
            f.setVisible(true);
            setVisible(false);
            

        }
    }
}

    
    private void boutondiago2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutondiago2ActionPerformed
        grille.activerDiagonaleMontante();
        repaint();
        finpartie();
    }//GEN-LAST:event_boutondiago2ActionPerformed

    private void chalengeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chalengeActionPerformed
       challengeActive = true;
      
    }//GEN-LAST:event_chalengeActionPerformed

    /**
     * @param args the command line arguments
     */
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FenetrePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FenetrePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FenetrePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FenetrePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FenetrePrincipale().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Affichercoups;
    private javax.swing.JButton Boutondiago;
    private javax.swing.JPanel PanneauBoutonsHorizontaux;
    private javax.swing.JPanel PanneauBoutonsVerticaux;
    private javax.swing.JPanel PanneauGrille;
    private javax.swing.JButton boutondiago2;
    private javax.swing.JButton chalenge;
    // End of variables declaration//GEN-END:variables
}
